# This is a basic workflow to help you get started with Actions

name: Java CI with Gradle 

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
             java-version: 1.8
      

      # Runs a set of commands using the runners shell
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      -name: Build with Gradle
        run: ./gradlew build
          
